### ISSUE TITLE
Installation failed on mac

### ISSUE THREAD

**Issue by fan70m** [fantastic-kit/fantastic-kit#56]
It appears to be complaining about missing library, thought it's using `rvm` instead of system ruby.

See stack trace below: 
```
➜  ~ source ~/.zshrc
Traceback (most recent call last):
	2: from /Users/fanychen/.fantastic-kit/bin/kit-check-update:3:in `<main>'
	1: from /Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': dlopen(/Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/x86_64-darwin17/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib (LoadError)
  Referenced from: /Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/x86_64-darwin17/readline.bundle
  Reason: image not found - /Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/x86_64-darwin17/readline.bundle
Traceback (most recent call last):
	2: from /Users/fanychen/.fantastic-kit/bin/kit-check-update:3:in `<main>'
	1: from /Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': dlopen(/Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/x86_64-darwin17/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib (LoadError)
  Referenced from: /Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/x86_64-darwin17/readline.bundle
  Reason: image not found - /Users/fanychen/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/x86_64-darwin17/readline.bundle
```

**Comment by arora-aman** [comment]
@fan70m  can you try https://stackoverflow.com/a/56870614/5396751?

I remember having versioning issues with GL libs on Mac previously

**Comment by arora-aman** [comment]
@fan70m I was unable to reproduce it on my end. Can you run the following and compare?

```bash
$ brew list --versions | grep ruby
ruby 2.6.5
$ where ruby
/usr/local/opt/ruby/bin/ruby
/usr/bin/ruby
```
